import regex

input relation Entry(min: usize, max: usize, c: string, passwd: string)

output relation Solution(password: string, nonce: usize)

Solution(passwd, nonce) :- Entry(min, max, c, passwd),
                    var pat = regex(c),
                    var m = regex_all_matches(pat, passwd),
                    var count = vec_len(m),
                    var nonce = min + max,
                    count >= min, count <= max.
